version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: typed-ast
    versions:
    - 1.4.2
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: jinja2
    versions:
    - 2.11.2
